#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
chruby 2.3.7
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/home/fbernier/.local/bin:$PATH"
export PATH=$PATH:$HOME/dotnet
export PATH="$PATH:$HOME/.dotnet/tools"

# OPAM configuration
. /home/fbernier/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
